version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    command: python main.py
    volumes:
      - .:/app

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: python consumer.py