version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: python consumer.py