# Generated by Django 3.2.8 on 2021-10-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProblemApp', '0003_auto_20211013_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='UsuarioEmail',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='UsuarioNome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='UsuarioSenha',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='UsuarioSobrenome',
            field=models.CharField(max_length=200),
        ),
    ]
